/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.emp.gl.tp.controller;

import com.emp.gl.tp.robot.IRobot;
import com.emp.gl.tp.robot.StateIndicator;

import java.awt.*;

/**
 *
 * @author fateh
 */
public class Controller extends javax.swing.JFrame {

    /**
     * Creates new form Controller
     */
    private IRobot robot;
    public Controller(IRobot robot) {
        this.robot = robot;
        this.setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Left = new javax.swing.JButton();
        Top = new javax.swing.JButton();
        Bottom = new javax.swing.JButton();
        Right = new javax.swing.JButton();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Left.setText("LEFT");
        Left.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftActionPerformed(evt);
            }
        });
        getContentPane().add(Left, java.awt.BorderLayout.LINE_START);

        Top.setText("TOP");
        Top.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TopActionPerformed(evt);
            }
        });
        getContentPane().add(Top, java.awt.BorderLayout.PAGE_START);

        Bottom.setText("BOTTOM");
        Bottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottomActionPerformed(evt);
            }
        });
        getContentPane().add(Bottom, BorderLayout.AFTER_LAST_LINE);

        Right.setText("RIGHT");
        Right.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightActionPerformed(evt);
            }
        });
        getContentPane().add(Right, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftActionPerformed
        robot.moveRobot(StateIndicator.LEFT);
    }//GEN-LAST:event_LeftActionPerformed

    private void TopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TopActionPerformed
        robot.moveRobot(StateIndicator.TOP);
    }//GEN-LAST:event_TopActionPerformed

    private void RightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RightActionPerformed
        robot.moveRobot(StateIndicator.RIGHT);
    }//GEN-LAST:event_RightActionPerformed

    private void BottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottomActionPerformed
        robot.moveRobot(StateIndicator.BOTTOM);
    }//GEN-LAST:event_BottomActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bottom;
    private javax.swing.JButton Left;
    private javax.swing.JButton Right;
    private javax.swing.JButton Top;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
